//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication7.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Randevular
    {
        public int Randevu_id { get; set; }
        public Nullable<int> kullanici_id { get; set; }
        public Nullable<int> doktor_id { get; set; }
        public Nullable<System.DateTime> Randevu_saat { get; set; }
    
        public virtual Doktorlar Doktorlar { get; set; }
        public virtual Kullanicilar Kullanicilar { get; set; }
    }
}
